/*
A Scientific Calculator in JAVA
 */
import javax.swing.*;
import com.sun.glass.events.*;

/**
 *
 * @author Suman Mahanty
 */
public class Calculator extends javax.swing.JFrame {
    double fnum;
    double snum;
    double result;
    String operation;
    ButtonGroup bg=new ButtonGroup();
    int state;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        super("SCIENTIFIC CALCULATOR");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jdisplay = new javax.swing.JTextField();
        j7 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        jmultiplication = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        jminus = new javax.swing.JButton();
        j0 = new javax.swing.JButton();
        jdecimal = new javax.swing.JButton();
        jplusminus = new javax.swing.JButton();
        jequals = new javax.swing.JButton();
        j1 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        jplus = new javax.swing.JButton();
        jbackspace = new javax.swing.JButton();
        jclear = new javax.swing.JButton();
        jroot = new javax.swing.JButton();
        jdivide = new javax.swing.JButton();
        jsinh = new javax.swing.JButton();
        jcosh = new javax.swing.JButton();
        jtanh = new javax.swing.JButton();
        jsin = new javax.swing.JButton();
        jcos = new javax.swing.JButton();
        jtan = new javax.swing.JButton();
        jlog = new javax.swing.JButton();
        jln = new javax.swing.JButton();
        jexp = new javax.swing.JButton();
        jpermutaion = new javax.swing.JButton();
        jcombination = new javax.swing.JButton();
        jfactorial = new javax.swing.JButton();
        jpi = new javax.swing.JButton();
        jpow = new javax.swing.JButton();
        javax.swing.JTextField jby = new javax.swing.JTextField();
        jdegree = new javax.swing.JRadioButton();
        jradian = new javax.swing.JRadioButton();
        jpow2 = new javax.swing.JButton();
        jpow3 = new javax.swing.JButton();
        joct = new javax.swing.JButton();
        jbin = new javax.swing.JButton();
        jhex = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jdisplay.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jdisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jdisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdisplayKeyTyped(evt);
            }
        });

        j7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j7.setText("7");
        j7.setToolTipText("");
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });

        j8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j8.setText("8");
        j8.setToolTipText("");
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });

        j9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j9.setText("9");
        j9.setToolTipText("");
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });

        jmultiplication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jmultiplication.setText("*");
        jmultiplication.setToolTipText("");
        jmultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmultiplicationActionPerformed(evt);
            }
        });

        j4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j4.setText("4");
        j4.setToolTipText("");
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        j5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j5.setText("5");
        j5.setToolTipText("");
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        j6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j6.setText("6");
        j6.setToolTipText("");
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        jminus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jminus.setText("-");
        jminus.setToolTipText("");
        jminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jminusActionPerformed(evt);
            }
        });

        j0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j0.setText("0");
        j0.setToolTipText("");
        j0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j0ActionPerformed(evt);
            }
        });

        jdecimal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jdecimal.setText(".");
        jdecimal.setToolTipText("");
        jdecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdecimalActionPerformed(evt);
            }
        });

        jplusminus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jplusminus.setText("±");
        jplusminus.setToolTipText("");
        jplusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jplusminusActionPerformed(evt);
            }
        });

        jequals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jequals.setText("=");
        jequals.setToolTipText("");
        jequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jequalsActionPerformed(evt);
            }
        });

        j1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j1.setText("1");
        j1.setToolTipText("");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j2.setText("2");
        j2.setToolTipText("");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        j3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j3.setText("3");
        j3.setToolTipText("");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        jplus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jplus.setText("+");
        jplus.setToolTipText("");
        jplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jplusActionPerformed(evt);
            }
        });

        jbackspace.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbackspace.setText("←");
        jbackspace.setToolTipText("");
        jbackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackspaceActionPerformed(evt);
            }
        });

        jclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jclear.setText("C");
        jclear.setToolTipText("");
        jclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclearActionPerformed(evt);
            }
        });

        jroot.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jroot.setText("√");
        jroot.setToolTipText("");
        jroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrootActionPerformed(evt);
            }
        });

        jdivide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jdivide.setText("/");
        jdivide.setToolTipText("");
        jdivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdivideActionPerformed(evt);
            }
        });

        jsinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jsinh.setText("sinh");
        jsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsinhActionPerformed(evt);
            }
        });

        jcosh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcosh.setText("cosh");
        jcosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcoshActionPerformed(evt);
            }
        });

        jtanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtanh.setText("tanh");
        jtanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtanhActionPerformed(evt);
            }
        });

        jsin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jsin.setText("sin");
        jsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsinActionPerformed(evt);
            }
        });

        jcos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcos.setText("cos");
        jcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcosActionPerformed(evt);
            }
        });

        jtan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtan.setText("tan");
        jtan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtanActionPerformed(evt);
            }
        });

        jlog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlog.setText("log");
        jlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogActionPerformed(evt);
            }
        });

        jln.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jln.setText("ln");
        jln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlnActionPerformed(evt);
            }
        });

        jexp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jexp.setText("exp");
        jexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexpActionPerformed(evt);
            }
        });

        jpermutaion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpermutaion.setText("P");
        jpermutaion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpermutaionActionPerformed(evt);
            }
        });

        jcombination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcombination.setText("C");
        jcombination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombinationActionPerformed(evt);
            }
        });

        jfactorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jfactorial.setText("!");
        jfactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfactorialActionPerformed(evt);
            }
        });

        jpi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jpi.setText("π");
        jpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpiActionPerformed(evt);
            }
        });

        jpow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpow.setText("x^y");
        jpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpowActionPerformed(evt);
            }
        });

        jby.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jby.setText("Created By: Suman Chandra Mahanty");
        jby.setEditable(false);
        jby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbyActionPerformed(evt);
            }
        });

        buttonGroup1.add(jdegree);
        jdegree.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jdegree.setText("d");
        jdegree.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jdegreeItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jradian);
        jradian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jradian.setText("r");
        jradian.setSelected(true);

        jpow2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpow2.setText("^2");
        jpow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpow2ActionPerformed(evt);
            }
        });

        jpow3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpow3.setText("^3");
        jpow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpow3ActionPerformed(evt);
            }
        });

        joct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        joct.setText("oct");
        joct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joctActionPerformed(evt);
            }
        });

        jbin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbin.setText("bin");
        jbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbinActionPerformed(evt);
            }
        });

        jhex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jhex.setText("hex");
        jhex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhexActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jradian)
                            .addComponent(jdegree))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jhex, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(jequals, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jby, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jplusminus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpow, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(joct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpow2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jpow3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jmultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jsinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jplus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpermutaion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jminus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jclear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jroot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdivide, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcombination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcosh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jexp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jfactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdivide, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jroot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jclear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcosh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtanh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jminus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlog, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jln, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jexp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jplus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpermutaion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcombination, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jplusminus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpow, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpow2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpow3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdegree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jradian))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jequals, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jhex, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jby, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(460, 470);
        this.setLocation(300, 100);
        this.setResizable(false);
    }//GEN-LAST:event_formWindowActivated

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j9.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j9ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j6.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j6ActionPerformed

    private void jplusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jplusminusActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=op*(-1);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jplusminusActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j3.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j3ActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j1.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j2.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j2ActionPerformed

    private void jrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrootActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=Math.sqrt(op);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jrootActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j7.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j7ActionPerformed

    private void jmultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmultiplicationActionPerformed
        // TODO add your handling code here:
        fnum=Double.parseDouble(jdisplay.getText());
        jdisplay.setText(null);
        operation="*";
    }//GEN-LAST:event_jmultiplicationActionPerformed

    private void jcoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcoshActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=Math.cosh(op);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jcoshActionPerformed

    private void jtanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtanhActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=Math.sinh(op);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jtanhActionPerformed

    private void jcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcosActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        if(state==1)
        {
            op=Math.toRadians(op);
        }
        op=Math.cos(op);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jcosActionPerformed

    private void jtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtanActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        if(state==1)
        {
            op=Math.toRadians(op);
        }
        op=Math.tan(op);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jtanActionPerformed

    private void jlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlnActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=Math.log(op);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jlnActionPerformed

    private void jexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexpActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=Math.exp(op);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jexpActionPerformed

    private void jcombinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombinationActionPerformed
        // TODO add your handling code here:
        fnum=Double.parseDouble(jdisplay.getText());
        jdisplay.setText(null);
        operation="c";
    }//GEN-LAST:event_jcombinationActionPerformed

    private void jfactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfactorialActionPerformed
        // TODO add your handling code here:
        int f=factorial(Integer.parseInt(String.valueOf(jdisplay.getText())));
        jdisplay.setText(String.valueOf(f));
    }//GEN-LAST:event_jfactorialActionPerformed

    private void jpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpowActionPerformed
        // TODO add your handling code here:
        fnum=Double.parseDouble(jdisplay.getText());
        jdisplay.setText(null);
        operation="^";
    }//GEN-LAST:event_jpowActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j8.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j8ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j4.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j4ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j5.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j5ActionPerformed

    private void j0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j0ActionPerformed
        // TODO add your handling code here:
        String inum=jdisplay.getText()+j0.getText();
        jdisplay.setText(inum);
    }//GEN-LAST:event_j0ActionPerformed

    private void jclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclearActionPerformed
        // TODO add your handling code here:
        jdisplay.setText("");
    }//GEN-LAST:event_jclearActionPerformed

    private void jbackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackspaceActionPerformed
        // TODO add your handling code here:
        String backspace=null;
        if(jdisplay.getText().length()>0)
        {
            StringBuilder sb=new StringBuilder(jdisplay.getText());
            sb.deleteCharAt(jdisplay.getText().length()-1);
            backspace=sb.toString();
            jdisplay.setText(backspace);
        }
    }//GEN-LAST:event_jbackspaceActionPerformed

    private void jdecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdecimalActionPerformed
        // TODO add your handling code here:
        if(!jdisplay.getText().contains("."))
        {
            jdisplay.setText(jdisplay.getText()+jdecimal.getText());
        }
    }//GEN-LAST:event_jdecimalActionPerformed

    private void jsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsinActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        if(state==1)
        {
            op=Math.toRadians(op);
        }
        op=Math.sin(op);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jsinActionPerformed

    private void jlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=Math.log(op)/2.302585092994046;
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jlogActionPerformed

    private void jpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpiActionPerformed
        // TODO add your handling code here:
        double op=Math.PI;
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jpiActionPerformed

    private void jsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsinhActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=Math.sinh(op);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jsinhActionPerformed

    private void jdisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdisplayKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_C)))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(c=='c' || c=='C')
        {
            jdisplay.setText("");
        }
    }//GEN-LAST:event_jdisplayKeyTyped

    private void jequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jequalsActionPerformed
        // TODO add your handling code here:
        String res;
        snum=Double.parseDouble(jdisplay.getText());
        if(operation=="+")
        {
            result=fnum+snum;
            res=String.format("%.2f",result);
            jdisplay.setText(res);
        }
        else if(operation=="-")
        {
            result=fnum-snum;
            res=String.format("%.2f",result);
            jdisplay.setText(res);
        }
        else if(operation=="*")
        {
            result=fnum*snum;
            res=String.format("%.2f",result);
            jdisplay.setText(res);
        }
        else if(operation=="/")
        {
            result=fnum/snum;
            res=String.format("%.2f",result);
            jdisplay.setText(res);
        }
        else if(operation=="^")
        {
            result=Math.pow(fnum, snum);
            res=String.format("%.2f",result);
            jdisplay.setText(res);
        }
        else if(operation=="p")
        {
            result=permutation(fnum,snum);
            res=String.format("%.2f",result);
            jdisplay.setText(res);
        }
        else if(operation=="c")
        {
            result=combination(fnum,snum);
            res=String.format("%.2f",result);
            jdisplay.setText(res);
        }
    }//GEN-LAST:event_jequalsActionPerformed

    private void jplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jplusActionPerformed
        // TODO add your handling code here:
        fnum=Double.parseDouble(jdisplay.getText());
        jdisplay.setText(null);
        operation="+";
    }//GEN-LAST:event_jplusActionPerformed

    private void jminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jminusActionPerformed
        // TODO add your handling code here:
        fnum=Double.parseDouble(jdisplay.getText());
        jdisplay.setText(null);
        operation="-";
    }//GEN-LAST:event_jminusActionPerformed

    private void jdivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdivideActionPerformed
        // TODO add your handling code here:
        fnum=Double.parseDouble(jdisplay.getText());
        jdisplay.setText(null);
        operation="/";
    }//GEN-LAST:event_jdivideActionPerformed

    private void jpermutaionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpermutaionActionPerformed
        // TODO add your handling code here:
        fnum=Double.parseDouble(jdisplay.getText());
        jdisplay.setText(null);
        operation="p";
    }//GEN-LAST:event_jpermutaionActionPerformed

    private void jbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbyActionPerformed

    private void jdegreeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jdegreeItemStateChanged
        // TODO add your handling code here:
        state=1;
    }//GEN-LAST:event_jdegreeItemStateChanged

    private void jpow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpow2ActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=Math.pow(op,2);
        jdisplay.setText(String.valueOf(op));                                     
    }//GEN-LAST:event_jpow2ActionPerformed

    private void jpow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpow3ActionPerformed
        // TODO add your handling code here:
        double op=Double.parseDouble(String.valueOf(jdisplay.getText()));
        op=Math.pow(op,3);
        jdisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jpow3ActionPerformed

    private void joctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joctActionPerformed
        // TODO add your handling code here:
        int ii=Integer.parseInt(jdisplay.getText());
        jdisplay.setText(Integer.toString(ii,8));
    }//GEN-LAST:event_joctActionPerformed

    private void jbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbinActionPerformed
        // TODO add your handling code here:
        int ii=Integer.parseInt(jdisplay.getText());
        jdisplay.setText(Integer.toString(ii,2));
    }//GEN-LAST:event_jbinActionPerformed

    private void jhexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhexActionPerformed
        // TODO add your handling code here:
        int ii=Integer.parseInt(jdisplay.getText());
        jdisplay.setText(Integer.toString(ii,16));
    }//GEN-LAST:event_jhexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton j0;
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbackspace;
    private javax.swing.JButton jbin;
    private javax.swing.JButton jclear;
    private javax.swing.JButton jcombination;
    private javax.swing.JButton jcos;
    private javax.swing.JButton jcosh;
    private javax.swing.JButton jdecimal;
    private javax.swing.JRadioButton jdegree;
    private javax.swing.JTextField jdisplay;
    private javax.swing.JButton jdivide;
    private javax.swing.JButton jequals;
    private javax.swing.JButton jexp;
    private javax.swing.JButton jfactorial;
    private javax.swing.JButton jhex;
    private javax.swing.JButton jln;
    private javax.swing.JButton jlog;
    private javax.swing.JButton jminus;
    private javax.swing.JButton jmultiplication;
    private javax.swing.JButton joct;
    private javax.swing.JButton jpermutaion;
    private javax.swing.JButton jpi;
    private javax.swing.JButton jplus;
    private javax.swing.JButton jplusminus;
    private javax.swing.JButton jpow;
    private javax.swing.JButton jpow2;
    private javax.swing.JButton jpow3;
    private javax.swing.JRadioButton jradian;
    private javax.swing.JButton jroot;
    private javax.swing.JButton jsin;
    private javax.swing.JButton jsinh;
    private javax.swing.JButton jtan;
    private javax.swing.JButton jtanh;
    // End of variables declaration//GEN-END:variables
    public int factorial(int x)
    {
        if(x==1)
	{
            return x;
	}
	else
	{
        	return (factorial(x-1)*x);
	}
    }
    public double permutation(double x,double y)
    {
        int n=(int)x,r=(int)y;
        r=n-r;
	n=factorial(n);
        r=factorial(r);
        r=n/r;
        double dd=(double)r;
	return dd;
    }
    public double combination(double x,double y)
    {
        int n=(int)x,r=(int)y,t;
        t=n-r;
        n=factorial(n);
        r=factorial(r);
        t=factorial(t);
        n=n/(t*r);
        double dd=(double)n;
        return dd;
    }
}
